name: terraform-fmt
description: Rewrite terraform files into canonical format
author: Daniel Flook

inputs:
  path:
    description: /home/bartek/terraform_aws
    required: true

runs:
  using: docker
  image: ../image/Dockerfile
  entrypoint: /entrypoints/fmt.sh

branding:
  icon: globe
  color: purple