name: learn-github-actions
on: [push]
jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      -uses: hashicorp/terraform-github-actions/fmt@v0.8.0
      -env: = {
    TF_ACTION_WORKING_DIR = "home/bartek/terraform_aws"
  }