name: terraform format
on: [pull_request]
jobs:
  terraform_format:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@master
      - name: 'terraform fmt'
        run: terraform fmt -check
